import os

EXPERIMENT_RUNNER_FILE = "AIExperiments_fast.x86_64"
EXPERIMENT_RUNNER_PATH = "/home/jimbo/Documents/University/Magistrale/II Anno/Tesi/Unity/Build/docker/"
GAME_DATA_FOLDER = "/home/jimbo/Documents/University/Magistrale/II Anno/Tesi/Unity/Build/docker/Data/"


NUM_PARALLEL_SIMULATIONS = 4
NUM_MATCHES_PER_SIMULATION = 1

GENOME_SQUARE_SIZE = 3
GENOME_MAP_SCALE = 2.5
GENOME_NUM_ROWS = 6
GENOME_NUM_COLUMNS = 6
GENOME_MIN_ROOM_WIDTH = 3
GENOME_MIN_ROOM_HEIGHT = 3
GENOME_MAX_ROOM_WIDTH = 5
GENOME_MAX_ROOM_HEIGHT = 5

EVOLVER_MATE_PROBABILITY = 0.3
EVOLVER_MUTATE_PROBABILITY = 0.3

# __MINIMUM_NUMBER_OF_MATCHES = 8
# NUM_PARALLEL_SIMULATIONS = min(os.cpu_count(), __MINIMUM_NUMBER_OF_MATCHES)
# NUM_MATCHES_PER_SIMULATION = max(1, math.ceil((__MINIMUM_NUMBER_OF_MATCHES / NUM_PARALLEL_SIMULATIONS)))
