import os

EXPERIMENT_RUNNER_FILE = "AIExperiments_fast.x86_64"
EXPERIMENT_RUNNER_PATH = os.getcwd() + "/"
GAME_DATA_FOLDER = os.getcwd() + "/Data/"

NUM_PARALLEL_SIMULATIONS = 2
NUM_MATCHES_PER_SIMULATION = 1

GENOME_SQUARE_SIZE = 3
GENOME_MAP_SCALE = 3
GENOME_NUM_ROWS = 6
GENOME_NUM_COLUMNS = 6
GENOME_MIN_ROOM_WIDTH = 2
GENOME_MIN_ROOM_HEIGHT = 2
GENOME_MAX_ROOM_WIDTH = 4
GENOME_MAX_ROOM_HEIGHT = 4

EVOLVER_MATE_PROBABILITY = 0.3
EVOLVER_MUTATE_PROBABILITY = 0.3

# __MINIMUM_NUMBER_OF_MATCHES = 8
# NUM_PARALLEL_SIMULATIONS = min(os.cpu_count(), __MINIMUM_NUMBER_OF_MATCHES)
# NUM_MATCHES_PER_SIMULATION = max(1, math.ceil((__MINIMUM_NUMBER_OF_MATCHES / NUM_PARALLEL_SIMULATIONS)))
