POINT_AD_SQUARE_SIZE = 1

POINT_AD_MIN_ROOM_RADIUS = 3
POINT_AD_MAX_ROOM_RADIUS = 9

POINT_AD_NUM_POINT_COUPLES = 15
POINT_AD_CORRIDOR_WIDTH = 3
POINT_AD_MAX_MAP_WIDTH = 64
POINT_AD_MAX_MAP_HEIGHT = 64
POINT_AD_MAP_SCALE = 2

HORIZONTAL_FIRST_CONNECTION = 0
VERTICAL_FIRST_CONNECTION = 1