SMT_SQUARE_SIZE = 1

SMT_ROOMS_NUMBER = 15
SMT_LINES_NUMBER = 5

SMT_MIN_ROOM_WIDTH = 8
SMT_MAX_ROOM_WIDTH = 20
SMT_MIN_ROOM_HEIGHT = 8
SMT_MAX_ROOM_HEIGHT = 20

SMT_MIN_SEPARATION = 3
SMT_MAX_SEPARATION = 10

SMT_CORRIDOR_WIDTH = 3

SMT_MAX_MAP_WIDTH = 100
SMT_MAX_MAP_HEIGHT = 100

SMT_CORRIDOR_WIDTH = 3
SMT_MAP_SCALE = 2

SMT_SOLVER_GENOME_SCALE = 1
SMT_SOLVER_LINE_WIDTH = 30
SMT_SOLVER_SCALE_FACTOR = 1000
