SMT_SQUARE_SIZE = 1

SMT_ROOMS_NUMBER = 12
SMT_LINES_NUMBER = 5

SMT_MIN_ROOM_WIDTH = 6
SMT_MAX_ROOM_WIDTH = 16
SMT_MIN_ROOM_HEIGHT = 6
SMT_MAX_ROOM_HEIGHT = 16

SMT_MIN_SEPARATION = 0
SMT_MAX_SEPARATION = 5

SMT_CORRIDOR_WIDTH = 3

SMT_MAX_MAP_WIDTH = 64
SMT_MAX_MAP_HEIGHT = 64
SMT_MIN_LINES_LENGTH = SMT_MAX_MAP_WIDTH/2

SMT_CORRIDOR_WIDTH = 3
SMT_MAP_SCALE = 2

SMT_SOLVER_GENOME_SCALE = 1
SMT_SOLVER_LINE_WIDTH = 15
SMT_SOLVER_SCALE_FACTOR = 1000
