SMT_SQUARE_SIZE = 1
SMT_ROOMS_NUMBER = 10

SMT_MIN_ROOM_WIDTH = 5
SMT_MAX_ROOM_WIDTH = 20
SMT_MIN_ROOM_HEIGHT = 5
SMT_MAX_ROOM_HEIGHT = 20

SMT_MIN_SEPARATION = 0
SMT_MAX_SEPARATION = 10

SMT_CORRIDOR_WIDTH = 3

SMT_LINES_NUMBER = 8

SMT_MAX_MAP_WIDTH = 100
SMT_MAX_MAP_HEIGHT = 100

SMT_CORRIDOR_WIDTH = 3
SMT_MAP_SCALE = 2

GENOME_SCALE_FOR_SMT_SOLVER = 1
