POINT_SQUARE_SIZE = 1

POINT_NUM_ROOMS = 15
POINT_MIN_ROOM_SIZE = 3
POINT_MAX_ROOM_SIZE = 18

POINT_NUM_POINT_COUPLES = 10
POINT_CORRIDOR_WIDTH = 3
POINT_MAX_MAP_WIDTH = 64
POINT_MAX_MAP_HEIGHT = 64
POINT_MAP_SCALE = 2

HORIZONTAL_FIRST_CONNECTION = 0
VERTICAL_FIRST_CONNECTION = 1